### ISSUE TITLE
Support browse versions of component

### ISSUE THREAD

**Issue by xoanmi** [backstage/mkdocs-techdocs-core#105]
It would be great to have a plugin/extension that would allow browsing between different versions of the same component. For example, through a dropdown that allows you to select the desired branch/tag of the source repo.

Something similar to [this](https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/docs/theme_overrides/assets/javascripts/version-select.js).

**Comment by gchenuet** [comment]
Agreed! Definitively a good nice to have!
