### ISSUE TITLE
pymdown-extensions vunerability

### ISSUE THREAD

**Issue by mrfelton** [backstage/mkdocs-techdocs-core#126]
GitHub dependabot is detecting a critical vulnerability in the version of pymdown-extensions that is currently bundled with mkdocs-techdocs-core.

See https://github.com/facelessuser/pymdown-extensions/security/advisories/GHSA-jh85-wwv9-24hv for details

Please update to the latest 10.x version which resolves the vulnerability.

**Comment by PeaWarrior** [comment]
Hey! Resolved, see #123 and #133.
