### ISSUE TITLE
Add clarify for base requirements for e.g. Python version

### ISSUE THREAD

**Issue by adamdmharvey** [backstage/mkdocs-techdocs-core#13]
Was having some problems with this plugin.  Took me a little digging, and then discovered this:

https://github.com/backstage/mkdocs-techdocs-core/blob/700fadcebbb5871974075e0c9aafdfaa113bd7e4/setup.py#L36

Turns out my Ubuntu image I was using was Python 3.6.  The error message wasn't super clear:

```
$ pip3 install mkdocs-techdocs-core
Collecting mkdocs-techdocs-core
  Could not find a version that satisfies the requirement mkdocs-techdocs-core (from versions: )
No matching distribution found for mkdocs-techdocs-core
```

Until I ran verbose and noticed this,

```
$ pip3 --verbose install mkdocs-techdocs-core
... snip ...
    The package https://files.pythonhosted.org/packages/2b/30/511099594d5128c13f703daef2d4770517f7433f8cc7593b58932ed3c0f4/
mkdocs_techdocs_core-0.0.13-py3-none-any.whl#sha256=fcb512088d3b4768ea002ff903b433ff89b08a30cce0139693cf36cca23ed50a
(from https://pypi.org/simple/mkdocs-techdocs-core/) (requires-python:>=3.7)
is incompatible with the pythonversion in use. Acceptable python versions are:>=3.7
  Could not find a version that satisfies the requirement mkdocs-techdocs-core (from versions: )
Cleaning up...
No matching distribution found for mkdocs-techdocs-core
... snip ...
```

So just to help avoid any challenges, a little section identifying this might be super helpful on the README just to help eliminate some challenges/save some people time.  I saw something similar on the techdocs core monorepo plugin.

Off to upgrade to Python 3.9 now... 😁 
Thanks!

**Comment by OrkoHunter** [comment]
Absolutely! It should be documented here in the README. :)

**Comment by adamdmharvey** [comment]
Thx!
