### ISSUE TITLE
mkdocs and mkdocs-material updates

### ISSUE THREAD

**Issue by SimonMarquis** [backstage/mkdocs-techdocs-core#145]
👋 Hi, the project is currently configured with these versions

- [mkdocs 1.2.2 (2021-07-18)](https://www.mkdocs.org/about/release-notes/#version-122-2021-07-18)
  https://github.com/backstage/mkdocs-techdocs-core/blob/b91a812ea3ee72beaa349cd66674f487d79e2241/requirements.txt#L4
- [mkdcos-material 9.1.3 (2023-03-14)](https://squidfunk.github.io/mkdocs-material/changelog/#9.1.3) 
https://github.com/backstage/mkdocs-techdocs-core/blob/b91a812ea3ee72beaa349cd66674f487d79e2241/requirements.txt#L12

I understand the complexity of updating these core components and why they are pinned. HTML markup is not documented as public API, and this might break things (#66).
That being said, we are currently missing a lot of nice features and bugfixes.

What would be the best approach to update these dependencies?
Are there any automated regression tests, or specific issues to check.
Or does [testing-dependencies-end-to-end](https://github.com/backstage/mkdocs-techdocs-core#testing-dependencies-end-to-end) is enough?

**Comment by jcarres-mdsol** [comment]
I am not maintainer here but I think upgrading to the latest 9.1.x material at least should be straightforward
I can't talk about mkdocs, the changelog looks scary for 1.4 and 1.5

**Comment by darrenyung** [comment]
Apologies but I second this need for updates. New updates has been introduced post-material-mkdocs v9.2 particularly the built-in Blog that is highly sought after by teams within my org.

**Comment by webark** [comment]
What does the scope of an update look like? I haven't looked at it and don't have a ton of familiarness with it, but someone I work with does. Any new features?

**Comment by alexlorenzi** [comment]
Hi - We've just [merged a change](https://github.com/backstage/mkdocs-techdocs-core/pull/154) that bumps the version of mkdocs-material to `9.2.7`. This did require us to up the lower bound of MkDocs to `1.5` which we were able to do, moving mkdocs-material to any higher version would have resulted in us needing to change the python version dependency, which is too large a change for right now.

The new version of `mkdocs-techdocs-core` is 1.3

**Comment by SimonMarquis** [comment]
While this update is very appreciated, it does not really solve the issue exposed here.
Can we keep this issue open?

**Comment by SimonMarquis** [comment]
@alexlorenzi, this is happening once again with:
- [mkdocs 1.6.0](https://github.com/mkdocs/mkdocs/releases/tag/1.6.0)
- [mkdocs-material 9.5.19](https://github.com/squidfunk/mkdocs-material/releases/tag/9.5.19)

See also:
- https://github.com/backstage/mkdocs-techdocs-core/issues/187
