### ISSUE TITLE
Upgrade mkdocs-material to 9.5.x

### ISSUE THREAD

**Issue by luksi1** [backstage/mkdocs-techdocs-core#166]
We would like to see `mkdocs-material` upgraded to 9.5.x to provide support for [grids](https://github.com/backstage/mkdocs-techdocs-core), among [other things](https://github.com/squidfunk/mkdocs-material/blob/master/CHANGELOG).

**Comment by eliazz95** [comment]
Same here!

**Comment by VincentLideboKjellman** [comment]
Would love this too!

**Comment by nickboldt** [comment]
Me three! also would be cool to include https://github.com/backstage/mkdocs-techdocs-core/issues/167 in the next release

**Comment by mgudmund** [comment]
I would love to get this in as well.

**Comment by omgaunicorn** [comment]
I've been having issues with kroki-mermaid diagrams becoming illegible in Dark Mode, and 9.5.x seems to solve those issues, so I'd like to see this added too.

**Comment by pwalleni** [comment]
Yes, please.

**Comment by omgaunicorn** [comment]
Hello @johnphilip283 , I already commented so I feel bad doing this, but saw you mention "vigorous tagging" in #168. Any chance to get some eyes on this please? If what is needed is manpower I could take a stab at a PR, but given how techdocs has pre-selections of what theme features are provided by default, I assume the team would want to take a look at that.

**Comment by alexlorenzi** [comment]
Hi, @omgaunicorn - I've created a PR that bumps `mkdocs-material` to the latest version and can now create docs that include the Grids, etc.

Once I've got it approved and merged I'll update this ticket.
