### ISSUE TITLE
Line highlighting in codeblocks has changed

### ISSUE THREAD

**Issue by bforbis** [backstage/mkdocs-techdocs-core#183]
I have recently just upgraded mkdocs-techdocs-core from v1.2.3 -> v1.3.5 and have been testing on my documentation smoke test page and noticed a significant change in how codeblock highlighting is visualized using the `hl_lines` directive.

**Version 1.2.3**
![image](https://github.com/backstage/mkdocs-techdocs-core/assets/16994570/fda7ba19-2a92-4d06-91b9-29e29e4cc367)

**Version ^1.3.3**
![image](https://github.com/backstage/mkdocs-techdocs-core/assets/16994570/4a12f273-4d19-4299-84c5-ed2a40f652ff)

I'm not sure if this was an intentional style change or is a bug, but the new way that line highlighting works is too subtle and easy to miss.

I've done some testing of versions in between and this seems to have been introduced in `mkdocs-techdocs-core@v1.3.3`, which bumped `mkdocs-material` to 9.4.14 

Looking at the css of the `.hll` and `.highlight` CSS class, it looks like the `background-color` was updated:

Old: `background-color: var(--md-code-hl-color)`
New: `background-color: var(--md-code-hl-color--light)`

This seems to have been changed in mkdocs-material as reported in https://github.com/squidfunk/mkdocs-material/issues/6017

**Comment by pwalleni** [comment]
Here too. Please fix. Thanks.

**Comment by awanlin** [comment]
Closing as this looks to be fixed in the upstream Backstage repo by https://github.com/backstage/backstage/pull/24809
