### ISSUE TITLE
Manage multiple techdocs in the same repository.

### ISSUE THREAD

**Issue by 4geru** [backstage/mkdocs-techdocs-core#184]
We develop in a mono-repository. Some teams, such as the frontend, backend, and QA teams, work together. We expect to manage two documents in the same repository.

I read those documents. However, I couldn't find the solution.
- [Creating and publishing your docs](https://backstage.io/docs/features/techdocs/creating-and-publishing/)
- [TechDocs FAQ](https://backstage.io/docs/features/techdocs/faqs/)

---
It would be nice to have a hierarchical structure like this.

```
$ tree .
.
├── README.md
├── backend-team
│   ├── README.md
│   ├── docs
│   └── mkdocs.yaml
├── backstage-promotion
│   ├── README.md
│   ├── docs
│   └── mkdocs.yaml
├── catalog-info.yaml
└── frontend-team
    ├── README.md
    ├── docs
    └── mkdocs.yaml
```

**Comment by bforbis** [comment]
Set the **backstage.io/techdocs-ref** annotation on your catalog component to the directory where your mkdocs.yaml is. So rather than the default, `dir:.`, you want something like `dir:backstage-team` for one component and `dir:frontend-team` for another.

**Comment by 4geru** [comment]
Thank you!! I can create the multiple document in the one place 👍 👍

**Comment by awanlin** [comment]
Closing as this looks resolved 👍
