### ISSUE TITLE
Support mkdocs 1.6

### ISSUE THREAD

**Issue by intentionally-left-nil** [backstage/mkdocs-techdocs-core#187]
Right now it's not possible to use mkdocs-techdocs-core and mkdocs 1.6, due to the very tight versioning coupling of mkdocs-material.

`mkdocs-material` needs to be bumped to 9.5.19 in order to allow (and sadly, require) mkdocs 1.6

**Comment by intentionally-left-nil** [comment]
Super cool that your github actions auto-close PR's.... maybe pinging reviewers to look at them would be better instead

**Comment by jonesbusy** [comment]
+1 here
