### ISSUE TITLE
Remove duplicated dependencies list

### ISSUE THREAD

**Issue by OrkoHunter** [backstage/mkdocs-techdocs-core#19]
We have listed Python dependencies in two places for this project
1. https://github.com/backstage/mkdocs-techdocs-core/blob/main/requirements.txt
2. `install_requires` in https://github.com/backstage/mkdocs-techdocs-core/blob/main/setup.py

This can cause inconsistencies when upgrading versions (like https://github.com/backstage/mkdocs-techdocs-core/pull/18). So we should keep just one - possibly reuse data from `requirements.txt` in `install_requires` of `setup.py`.

**Comment by iamansoni** [comment]
I would like to work on this task; you can assign it to me.
Also, will it be a good solution if I make `requirements.txt` to be read as a file in the `setup.py` and pass it as a list of strings to `install_requires` ?

**Comment by OrkoHunter** [comment]
Sounds good to me. @iamansoni
