### ISSUE TITLE
Format image size

### ISSUE THREAD

**Issue by fletchgqc** [backstage/mkdocs-techdocs-core#218]
How can I set image size in TechDocs?

Some internet searching led me to https://python-markdown.github.io/extensions/attr_list/ but this is not enabled by default and I can't get it working. See also https://squidfunk.github.io/mkdocs-material/reference/images/

Should this extension be added, or if not, how should one format an image?

**Comment by vanchaxy** [comment]
You can use `width` and `height` attributes.

E.g. In `.md` file:
```
![](wip.webp){ width="300" }

![](wip.webp){ width="600" }

![](wip.webp){ width="900" }
```

In backstage:
![image](https://github.com/user-attachments/assets/4939213a-5ba5-412f-8860-50a61e8bb6cc)

**Comment by fletchgqc** [comment]
Thanks, that works.
