### ISSUE TITLE
Add mkdocs-git-revision-date-localized-plugin

### ISSUE THREAD

**Issue by julioz** [backstage/mkdocs-techdocs-core#38]
Backstage documentation already uses the [git-revision-date-localized plugin](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin) to render its docs, would it make sense to include it as part of the techdocs-core toolbox?

I've noticed [some other references to it](https://github.com/backstage/backstage/issues/5064#issuecomment-826459865) in issues before, so am assuming more people are interested in the functionality (my org included).

**Comment by garyniemen** [comment]
@emmaindal do you have any comments on this?

**Comment by emmaindal** [comment]
@garyniemen thanks for mentioning me, I'll take a look at the extension. @julioz Thanks for opening the issue, we will take a deeper into the extension and do some evaluation. In the meanwhile, can you list some use cases of what problems this extension solves for you/others? And the benefits of having it as a part of techdocs-core versus adding it manually depending on needs.

**Comment by julioz** [comment]
@emmaindal Thanks for the ping.

> In the meanwhile, can you list some use cases of what problems this extension solves for you/others?

Did you have a chance to skim over the links on this issue's description? I think this one [covers good part of the usecase for the plugin](https://github.com/backstage/backstage/issues/5064#issuecomment-826459865).

> And the benefits of having it as a part of techdocs-core versus adding it manually depending on needs.

I see two benefits for adopters:

* Getting the behavior out of the box, which would allow us (and new adopters) to rely on the provided setup for TechDocs, instead of wrapping it with custom logic (in Dockerfiles, mkdocs setup, etc) to install the plugin.
* Mainly, leverage the thorough testing cycle the TechDocs maintainers already run for everything-backstage. Currently, we have to manually verify new versions of TechDocs are compatible with our internally-maintained mkdocs-setup and plugin version.

From what I can tell, the official backstage microsite _already uses the plugin_, so why not provide it with the other bundled ones?

<img width="1256" alt="Screenshot 2021-12-06 at 14 08 39" src="https://user-images.githubusercontent.com/1541701/144851644-65df1386-4a51-4201-9603-850c1aaa5db7.png">

**Comment by julioz** [comment]
Hi @emmaindal, did you have a chance to review the plugin's integration? Thank you.

**Comment by saadazizgc** [comment]
+1 on the follow-up!

It would be really useful to be able to see the last-updated-time out of the box, without having to override docs.

It would be useful if there was a way to add template overrides in a plugin (i.e. override the source-file.html).

**Comment by alexef** [comment]
I'm trying to use it, added it on the image, however it fails with:
```
DEBUG    -  Running 3 `config` events[38](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-38)WARNING  -  [git-revision-date-localized-plugin] Unable to find a git directory and/or git is not installed. To ignore this error, set option 'fallback_to_build_date: true'[39](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-39)Traceback (most recent call last):[40](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-40)  File "/usr/local/bin/mkdocs", line 8, in <module>[41](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-41)sys.exit(cli())[42](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-42)  File "/usr/local/lib/python3.9/dist-packages/click/[core.py, Opens in a new window](http://core.py/)", line 1130, in __call__[43](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-43)return self.main(*args, **kwargs)[44](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-44)  File "/usr/local/lib/python3.9/dist-packages/click/[core.py, Opens in a new window](http://core.py/)", line 1055, in main[45](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-45)rv = self.invoke(ctx)[46](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-46)  File "/usr/local/lib/python3.9/dist-packages/click/[core.py, Opens in a new window](http://core.py/)", line 1657, in invoke[47](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-47)return _process_result(sub_ctx.command.invoke(sub_ctx))[48](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-48)  File "/usr/local/lib/python3.9/dist-packages/click/[core.py, Opens in a new window](http://core.py/)", line 1404, in invoke[49](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-49)return ctx.invoke(self.callback, **ctx.params)[50](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-50)  File "/usr/local/lib/python3.9/dist-packages/click/[core.py, Opens in a new window](http://core.py/)", line 760, in invoke[51](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-51)return __callback(*args, **kwargs)[52](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-52)  File "/usr/local/lib/python3.9/dist-packages/mkdocs/__main__.py", line 250, in build_command[53](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-53)[build.build, Opens in a new window](http://build.build/)(cfg, dirty=not clean)[54](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-54)  File "/usr/local/lib/python3.9/dist-packages/mkdocs/commands/[build.py, Opens in a new window](http://build.py/)", line 270, in build[55](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-55)config = [config.plugins.run, Opens in a new window](http://config.plugins.run/)_event('config', config)[56](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-56)  File "/usr/local/lib/python3.9/dist-packages/mkdocs/[plugins.py, Opens in a new window](http://plugins.py/)", line 520, in run_event[57](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-57)result = method(item, **kwargs)[58](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-58)  File "/usr/local/lib/python3.9/dist-packages/mkdocs_git_revision_date_localized_plugin/[plugin.py, Opens in a new window](http://plugin.py/)", line 72, in on_config[59](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-59)self.last_site_revision_timestamp = self.util.get_git_commit_timestamp([60](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-60)  File "/usr/local/lib/python3.9/dist-packages/mkdocs_git_revision_date_localized_plugin/[util.py, Opens in a new window](http://util.py/)", line 147, in get_git_commit_timestamp[61](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-61)raise err[62](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-62)  File "/usr/local/lib/python3.9/dist-packages/mkdocs_git_revision_date_localized_plugin/[util.py, Opens in a new window](http://util.py/)", line 118, in get_git_commit_timestamp[63](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-63)    git = self._get_repo(realpath)[64](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-64)  File "/usr/local/lib/python3.9/dist-packages/mkdocs_git_revision_date_localized_plugin/[util.py, Opens in a new window](http://util.py/)", line 40, in _get_repo[65](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-65)self.repo_cache[path] = Repo(path, search_parent_directories=True).git[66](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-66)  File "/usr/local/lib/python3.9/dist-packages/git/repo/[base.py, Opens in a new window](http://base.py/)", line 265, in __init__[67](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-67)raise InvalidGitRepositoryError(epath)[68](https://stack.gygservice.com/docs/default/Component/bi-data-guide#line-68)git.exc.InvalidGitRepositoryError: /tmp/backstage-2viw9e/docs```

I'm guessing we're missing to create `.git` during the prepare step.

Did anyone succeed at that?

**Comment by alexef** [comment]
I'm trying to use it, added it on the image, however it fails with:

```
DEBUG    -  Running 3 `config` events[38]
WARNING  -  [git-revision-date-localized-plugin] Unable to find a git directory and/or git is not installed. To ignore this error, set option 'fallback_to_build_date: true'
raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /tmp/backstage-2viw9e/docs
```

I'm guessing we're missing to create `.git` during the prepare step.

Did anyone succeed at that?

**Comment by awanlin** [comment]
Just wanted to mention that this won't work with the out-of-the-box TechDocs setup as it only pulls down the files and not the git history. This would work for those using the CI/CD pattern. 

@julioz you said: "Backstage documentation already uses the [git-revision-date-localized plugin](https://github.com/timvink/mkdocs-git-revision-date-localized-plugin) to render its docs" can you point out where it's being used, please?

**Comment by julioz** [comment]
@awanlin Absolutely: https://github.com/backstage/mkdocs-monorepo-plugin/blob/master/requirements.txt#L5

**Comment by awanlin** [comment]
Thanks @julioz that's interesting, it's only in the `mkdocs-monorepo-plugin`. I thought maybe it was in the main Bacstage repo and I just missed it.

**Comment by awanlin** [comment]
Just want to mention that this would break our TechDocs implementation as we don't pull in the git history so would not like to see this added unless there is a solution for that. We do like the idea of what this plugin offers though.

There's a [discord thread](https://discord.com/channels/687207715902193673/1106234902741008444) on this topic and I've mentioned there that maybe the proper solution is to make it easer for people to add plugins at a global level instead of having to have them added to `mkdocs-techdocs-core`

**Comment by saadazizgc** [comment]
> 

Is there any intention to start pulling the git history in the CI/CD pipelines?

**Comment by kunickiaj** [comment]
Also worth noting `mkdocs-git-revision-date-localized-plugin` has a significant peformance hit especially on large repos such as monorepos. I'm still looking for a better way to handle this.

**Comment by awanlin** [comment]
Looks like someone has created a PR to support a default plugins feature: https://github.com/backstage/backstage/pull/18699

**Comment by agentbellnorm** [comment]
> Worth to mention - we use our own techdocs image which has custom plugins installed. It simply uses the spotify/techdocs image as base, so it is just an extended version of it.

This is the way. I'm also adding some docs on how to use mkdocs plugins besides the ones in this core plugin here https://github.com/backstage/backstage/pull/19607.

Closing this issue as we will not add `mkdocs-git-revision-date-localized-plugin` to `mkdocs-techdocs-core`
