### ISSUE TITLE
Non Breaking Space (NBSP) in SVG breaks image rendering

### ISSUE THREAD

**Issue by trietsch** [backstage/mkdocs-techdocs-core#49]
I regularly create SVGs using diagrams.net, which often includes non breaking space characters (shown by IDEs as NBSP). When these characters occur somewhere in the SVG, the entire image is not rendered.

MkDocs does not have this issue, when running `mkdocs serve` locally, the image is rendered properly.

**Comment by jankeesvanandel** [comment]
I have the same issue. It seems that there is an error transforming the SVG into a data-URL.
When I render the SVG directly in the browser, there is no issue, but when I open the data-URL that is generated in the Backstage page, I get an error like this: `This page contains the following errors:
error on line 4 at column 16398: Encoding error
`

**Comment by vierno** [comment]
I've had this problem with other unicode characters as well (`ç` and `ã`).

**Comment by iamEAP** [comment]
Hey y'all.  Anyone still experiencing this with a version of `@backstage/plugin-techdocs` above `v1.1.1`?

Thinking it may have been resolved by https://github.com/backstage/backstage/pull/11054
