### ISSUE TITLE
Add support for literate-nav in techdocs

### ISSUE THREAD

**Issue by punkle** [backstage/mkdocs-techdocs-core#51]
It would be great if liberate-nav was supported as it allows more dynamic mapping of mkdocs links.

**Comment by andrewthauer** [comment]
Interesting. Haven't seen that one. However, we have been using [awesome-pages](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin) in a custom container for quite a while. It seems to cover a similar use case. It also interestingly enough allows us to avoid having an `mkdocs.yaml` file entirely, which we generate dynamically.

**Comment by maayanshem** [comment]
Hey, I asked for it, but I really think I'll just generate the `mkdocs.yml` dynamically. It makes sense because I intend to use like 1% of `literate-nav` capabilities.
