### ISSUE TITLE
Describe the different extensions and plugins included in TechDocs Core

### ISSUE THREAD

**Issue by emmaindal** [backstage/mkdocs-techdocs-core#6]
We currently have a [list](https://github.com/backstage/mkdocs-techdocs-core#mkdocs-plugins-and-extensions) of supported extension and plugins you get by default by using the TechDocs Core plugin. 

This list could include a short description of the extension and how you can use it to give the users a clear understanding of the different extensions and plugins the techdocs core plugin supports, without having to go and read the official documentation for it.

**Comment by iamansoni** [comment]
Hi, I'm new to the contribution and this seems to be a really simple and easy to solve issue; can I start working on it!

**Comment by OrkoHunter** [comment]
@iamansoni Yes, go ahead!
