### ISSUE TITLE
mkdocs-techdocs-core 1.0.2 is broken

### ISSUE THREAD

**Issue by aladjadj** [backstage/mkdocs-techdocs-core#62]
Since the latest version, we can't build anymore our doc.

Release:https://pypi.org/project/mkdocs-techdocs-core/1.0.2

With version 1.0.1, the build works fine.

**Comment by aladjadj** [comment]
After some diff between techdocs-core 1.0.2 && 1.0.1

I think the probleme is with mkdocs-monorepo-plugin, if I rollback this plugin to the version 1.0.0, the build works fine, but not with 1.0.1

**Comment by nickstolwijk** [comment]
It looks like the fix was merged, but the 1.0.2 release is re-released. Was that a mistake?
