### ISSUE TITLE
Add mkdocs-glightbox to allow images to be zoom

### ISSUE THREAD

**Issue by kenny-chow-my** [backstage/mkdocs-techdocs-core#75]
As some users publish architecture diagrams in png or jpg format, they are very tiny to view in the default content area. Allowing a Lightbox experience will greatly improve the readability of such content. 

Mkdocs already supports using the glightbox plugin here: https://squidfunk.github.io/mkdocs-material/reference/images/#lightbox

Can we enable this in TechDocs?

**Comment by iamEAP** [comment]
👋 Hey!  I responded with this in [a relevant thread in discord](https://discord.com/channels/687207715902193673/1002685054864076841), but here's a copy:

> _TechDocs is kind of unique in that, unlike a standard mkdocs site that is built and hosted at some location, the built HTML content gets rendered within the context of a broader application (Backstage).  Any JavaScript that gets loaded and run would therefore have access to a lot more than a typical mkdocs site (e.g. local storage values, cookies, access tokens, that might be tied to a source code provider, a cloud provider, etc)._
>
> _...To mitigate the risk associated with that, we filter out all scripts by default.  This includes scripts added by mkdocs plugins like this underlying feature exposed by `mkdocs-material`_
>
> _..._
>
> > _...the only solution to achieve this functionality (open a lightbox to increase the image size) is via an addon, right?_
>
> _Correct!  Folks have wanted this from time to time as well, see https://github.com/backstage/backstage/issues/10270_
>
> _One possible approach would be to create an addon that loads in and instantiates the equivalent of that glightbox within the Addon code itself.  ...This is not too dissimilar to how this mermaid diagram addon works: https://github.com/johanneswuerbach/backstage-plugin-techdocs-addon-mermaid_

Given the above, I'll be closing this specific issue, as it's not technically feasible to add/enable this particular plugin.

Instead, I encourage you or anyone looking for this functionality to create [a TechDocs Addon](https://backstage.io/docs/features/techdocs/addons) that achieves the same effect.  The best place to coordinate that would likely be in this issue: https://github.com/backstage/backstage/issues/10270

**Comment by connorads** [comment]
Looks like a lightbox TechDocs Addon was added in https://github.com/backstage/backstage/pull/16122
https://backstage.io/docs/reference/plugin-techdocs-module-addons-contrib.lightbox/
